meta_title: "DrincApp"
meta_description: "Drinks anytime 24/7 - Get your favorite beverages delivered"
meta_image: "background.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@lewagonbrussels" # indispensable pour les Twitter Cards
